### ISSUE TITLE
Implement UnwindSafe?

### ISSUE THREAD

**Issue by akhilles** [stjepang/concurrent-queue#2]
Can `ConcurrentQueue` implement the [`UnwindSafe`](https://doc.rust-lang.org/std/panic/trait.UnwindSafe.html) trait? Currently, it can't be used within `panic::catch_unwind`:

> the type `std::cell::UnsafeCell<std::mem::MaybeUninit<std::sync::Arc<pala_types::message::Message<pala_types::transaction::LedgerTx>>>>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary

**Comment by stjepang** [comment]
Yes it can :) I just published a new version where `ConcurrentQueue` implements `UnwindSafe` and `RefUnwindSafe`.
